- README.md
Fixed some typo's and a reference to an unknown variable.
> Fix some ready typo's.

- keywords.txt
- library.properties
This PR add keywords file and library.property file.
> Add keywords and library.property files

- library.properties
you need update this file every time for new release
> Update library version

- library.json
Requested in https://community.platformio.org/t/library-registry-points-to-an-outdated-fork/144
> Use tagged source code from repo; fix invalid platform IDs

- PJON.h
This is basically the same as #65 but rebased to the new version.
- NULL is a actually '(void*)0' and shouldn't be used on non-pointer types.
- const correctness for send function
- FAIL is set to 0x100 which is bigger than max of uint8
> Fix some compiler warnings (for v3.0)

- PJON.h
Sender id (and sender bus id if shared).
Reply function.
Configurable max packet size and queue size.
Packet type for detecting incoming packet structure.
Replaced id parameter with packet_info in receive callback function.
> Suggested PJON enhancements

- strategies/EthernetTCP/EthernetLink.h
Mismatch using uint32_t vs unsigned long.
> Fixed compilation problem on 32 bit devices

- PJON.h
- README.md
- strategies/README.md
- utils/digitalWriteFast.h
Hi, i added possibility to exclude unused strategy files, and conditional definition to macro `__digitalPinToBit` (for MySensors library compatibility which already defines the same macro)
> Added possibility to reduce memory footprint by turning off including and digitalWriteFast compat

- interfaces/ARDUINO/PJON_IO.h
- strategies/PJON_Strategies.h
- strategies/SoftwareBitBang/Timing.h
adding support for the attiny44/84
> Support for Attiny44/84

- examples/ARDUINO/Local/GlobalUDP/PingPong/Receiver/Receiver.ino
- examples/ESP8266/Local/GlobalUDP/PingPong/Receiver/Receiver.ino
- examples/ESP8266/Local/GlobalUDP/PingPong/Transmitter/Transmitter.ino
- interfaces/ARDUINO/TCPHelper_ARDUINO.h
- interfaces/ARDUINO/UDPHelper_ARDUINO.h
- strategies/EthernetTCP/EthernetLink.h
- strategies/GlobalUDP/GlobalUDP.h
- strategies/LocalUDP/LocalUDP.h
Added support for ESP8266 to GlobalUDP (good performance) and LocalUDP
(low performance on this platform if equal amounts of packets go in and
out).
> Added support for ESP8266 to GUDP+LUDP

- examples/ARDUINO/Local/EthernetTCP/SoftwareBitBangSurrogate/RemoteWorker/Transmitter/Transmitter.ino
- examples/ARDUINO/Local/EthernetTCP/SoftwareBitBangSurrogate/Surrogate/Surrogate.ino
- examples/LINUX/EthernetTCP/RemoteWorker/README.md
- examples/LINUX/EthernetTCP/RemoteWorker/Transmitter/Makefile
- examples/LINUX/EthernetTCP/RemoteWorker/Transmitter/README.md
- examples/WINX86/Local/EthernetTCP/RemoteWorker/README.md
- examples/WINX86/Local/EthernetTCP/RemoteWorker/RemoteWorker.sln
- examples/WINX86/Local/EthernetTCP/RemoteWorker/Transmitter/Transmitter.cpp
- examples/WINX86/Local/EthernetTCP/RemoteWorker/Transmitter/Transmitter.vcxproj
- examples/WINX86/Local/EthernetTCP/RemoteWorker/Transmitter/Transmitter.vcxproj.filters
- interfaces/LINUX/TCPHelper_POSIX.h
This allows a Windows process to parttake in a SWBB bus via an Ethernet
TCP connection to a Surrogate Arduino device.
> Added Windows RemoteWorker example

- PJONRouter.h
- PJONRouterDynamic.h
- PJONSimpleSwitch.h
- PJONSwitch.h
- examples/ARDUINO/Local/SoftwareBitBang/Switch/SimpleSwitch/SimpleSwitch.ino
- examples/ARDUINO/Local/SoftwareBitBang/Switch/Switch/Switch.ino
- examples/ARDUINO/Network/SoftwareBitBang/Router/Router/Router.ino
- examples/ARDUINO/Network/SoftwareBitBang/Router/RouterDynamic/RouterDynamic.ino
- examples/ARDUINO/Network/SoftwareBitBang/SegmentedSwitch/Switch/Switch.ino
- examples/ARDUINO/Network/SoftwareBitBang/Switch/Switch/Switch.ino
Added PJONSimpleSwitch with reduced memory requirements.
Fixed a bug in PJONRouter.
Added examples for PJONSimpleSwitch, PJONRouter and PJONRouterDynamic.
Changed existing relevant examples according to parameter changes.
All tested.
> Added PJONSimpleSwitch, routing related changes

- examples/ARDUINO/Local/ThroughLoRa/BlinkTest/Receiver/Receiver.ino
- examples/ARDUINO/Local/ThroughLoRa/BlinkTest/Transmitter/Transmitter.ino
- strategies/ThroughLoRa/README.md
- strategies/ThroughLoRa/ThroughLora.h
Added Thorugh Lora documentation
Added more API's to ThroughLoRa.h
Deleted unused code in blinkTest Examples for lora
> Documentation update

- interfaces/ARDUINO/PJON_IO.h
Added support for AtMega1284P, tested with Serial strategy. I'll test SoftwareBitBang soon
> Added support for AtMega1284P

- library.properties
- src/interfaces/ARDUINO/PJON_ARDUINO_Interface.h
- src/interfaces/ARDUINO/TCPHelper_ARDUINO.h
- src/interfaces/ARDUINO/UDPHelper_ARDUINO.h
- src/strategies/PJON_Strategies.h
this will add base ESP32 support.
Not tested yet in functionality - only minor compiling work.
> add ESP32 support (#207)

- src/interfaces/LINUX/PJON_LINUX_Interface.h
> Added support for Android 

- library.json
> fix typo in library.json

- examples/ESP32/ESPNOW/PlatformIO/Device1/.gitignore
- examples/ESP32/ESPNOW/PlatformIO/Device1/.travis.yml
- examples/ESP32/ESPNOW/PlatformIO/Device1/.vscode/extensions.json
- examples/ESP32/ESPNOW/PlatformIO/Device1/include/README
- examples/ESP32/ESPNOW/PlatformIO/Device1/lib/README
- examples/ESP32/ESPNOW/PlatformIO/Device1/platformio.ini
- examples/ESP32/ESPNOW/PlatformIO/Device1/src/main.cpp
- examples/ESP32/ESPNOW/PlatformIO/Device1/test/README
- examples/ESP32/ESPNOW/PlatformIO/Device2/.gitignore
- examples/ESP32/ESPNOW/PlatformIO/Device2/.travis.yml
- examples/ESP32/ESPNOW/PlatformIO/Device2/.vscode/extensions.json
- examples/ESP32/ESPNOW/PlatformIO/Device2/include/README
- examples/ESP32/ESPNOW/PlatformIO/Device2/lib/README
- examples/ESP32/ESPNOW/PlatformIO/Device2/platformio.ini
- examples/ESP32/ESPNOW/PlatformIO/Device2/src/main.cpp
- examples/ESP32/ESPNOW/PlatformIO/Device2/test/README
- examples/ESP32/ESPNOW/PlatformIO/espnowpio.code-workspace
- src/interfaces/ARDUINO/ESPNOWHelper.h
> Fix issue #322 espnow set channel issue

- examples/ESP8266/Local/MQTTTranslate/EnvironmentController/EnvironmentController.ino
Demonstrates the MIRROR_TRANSLATE mode for creating MQTT devices.
> Added ESP8266 MQTT EnvironmentController.ino example

- src/strategies/DualUDP/DualUDP.h
Also increased speed to about average 75 packets/s
> DualUDP avoid sending too fast, getting contention on ESP

- src/strategies/ESPNOW/ESPNOW.h
Stop searching when usng nodeID of 255 and instead use the intended MAC recepient.
Requires more testing, but early indication it seems to resolve my issue #369.
> Find correct MAC for ESPNOW
