- PJON.h
- library.properties
Hello Giovanni! Would you approve these changes to get compatibility with ESP8266 in (80mHz in COMPATIBILITY_MODE).
I've tested it on ESP-8266 ( in the company of 8266-v.1, 8266-v.7, and Arduino uno v3).
Of course, in case of interact with 5v boards, it needs to use ttl 5-3.3 converter. I used BSS138 with pulldonw (instead of pullup) resistors - works absolutely fine! Actually, it works even in case of direct pin connection, but it's wrong apporoach.
One more thing - ESP8266 will not work with your examples with 10s synconous cycle - it reboots. Just change this time to 1 or 2 seconds, or put yelds in the cycle.
If you interested in this, I could make two level COMPATIBILITY_MODE (8mhZ,16mhz).
With regards, Alexey Grishin.
240974a@gmail.com
> support ESP 8266 (80mHz in COMPATIBILITY_MODE)

- examples/NetworkAnalysis/Transmitter/Transmitter_esp8266
Default example doesn't work on esp8266 (esp12) boards as the loop function doesn't feed the watchdog timer correctly. Figured I'd post this full example for now (I am using PlatformIO-based project structure, not Arduino IDE).
Wondering if including a conditional #ifdef for esp8266 in the PJON::update() function would be an even better fix.
> Fixes watchdog timer resets (must feed at least once within 8 seconds)

- PJON.cpp
- PJON.h
- includes/digitalWriteFast.h
- library.properties
Modified PJON.cpp and PJON.h
- Added support for the Arduino Zero. 
Able to achieve the following speeds between two Arduino Zero
Absolute com speed: 5215.20B/s
Practical bandwidth: 4346.00B/s
Packets sent: 2173.00
Mistakes (error found with CRC) 0.00
Fail (no answer from receiver) 0
Busy (Channel is busy or affected by interference) 0
Accuracy: 100.00 %  
- All comparison typecasted to preserve proper format between platforms. Comparisons
on AVR defaults to 16 bit unless typecasted, while it defaults to 32 bits on SAMD
This can give problems when comparison is made with timer functions such as millis(),
micros(), delay() and delaymicroseconds().
The function micros() and millis() both returns a unsigned long (uint32_t) on AVR and SAMD.
Delay argument is typecasted (unsigned long) or …
> Support for Arduino Zero

- library.json
Specifying a version in the descriptor locks things at a specific release. Let PlatformIO crawler scan the tags regularly and update automatically.
> Let the crawler auto-resolve released versions from github tags

- PJON.h
Example usage
```c++
#define NOT_ASSIGNED 0
#define BROADCAST 255
#include <PJON.h>
```
> Allow to modify reserved addresses (BROADCAST and NOT_DEFINIED)

- examples/Local/OverSamplingSimplex/Receiver/Receiver.ino
- examples/Local/OverSamplingSimplex/Transmitter/Transmitter.ino
This example seems not effectively using SIMPLEX communication mode, but it leaves the communication mode to default HALF_DUPLEX, so to switch to SIMPLEX we should unassign
the unused pin, or call set_communication_mode(SIMPLEX)
> Please check OverSamplingSimplex example

- PJON.h
More details in commit message.
The reason for extracting functions is that an outside function that needs to call the send_string function to get immediate send status had a hard time doing so, because the message has to contain sender id and bus id(s) if so configured, and duplicating this message composition outside of PJON is bad.
Now possible:
uint8_t new_length = pjon->get_total_length(length);
char str[new_length];
pjon->compose_message(remote_bus, str, (const char *)message, length);
status = pjon->send_string(remote_id, str, new_length, pjon->get_header_byte() | CUSTOM_BIT);
> Static buffers. Extracted functions.

- documentation/io-setup.md
As suggested in https://github.com/gioblu/PJON/issues/104 it'd be a good idea to illustrate that using NOT_ASSIGNED means that we're necessarily in Simplex mode, which needs to be manually set with bus.strategy.set_communication_mode(SIMPLEX);
Adding it to the example would help new comers to PJON.
> Update io-setup doc with set_communication_mode()

- examples/Local/Extender/Extender/Extender.ino
- examples/Local/Extender/README.md
- examples/Local/Extender/Tunneler/ExtenderA/ExtenderA.ino
- examples/Local/Extender/Tunneler/ExtenderB/ExtenderB.ino
These examples can be used for segmenting a bus into mutiple media, for
example for range extension or spanning wired and wireless with the same
bus.
Also show is a pair of extenders working together to tunnel SWBB traffic
back and forth through an Ethernet LAN using the LocalUDP strategy.
> Added Extender examples

- strategies/SoftwareBitBang/specification/obsolete/PJDL-specification-v1.0.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- interfaces/PJON_Interfaces.h
- interfaces/WINX86/PJON_WINX86_Interface.h
- interfaces/WINX86/Serial/Serial.cpp
- interfaces/WINX86/Serial/Serial.h
- strategies/ThroughSerial/ThroughSerial.h
Added interface implementation to make it possible to compile PJON on Windows. 
Only serial port communication is supported (ThroughSerial strategy).
test code: 
Windows test client: https://gist.github.com/Girgitt/a560e3e8f1b1e7561a0162e7ef6fcc36
(it is required to add PJON\interfaces\WINX86\Serial\serial.cpp file to resources in VS 2016 Express otherwise linking will fail)
Arduino test client: https://gist.github.com/Girgitt/f5b1d2d92d3e734f5d94ff38584d2051
> Added interface implementation for Windows x86 platform

- interfaces/WINX86/PJON_WINX86_Interface.h
- strategies/ThroughSerial/ThroughSerial.h
The initial WINX86 interface implementation causes PJON to utilize single core at 100% due to unnecessarily frequent polling on serial port by receive_byte method. 
Since ThroughSerial uses hardware-controlled reception there is no need to poll it for incoming bytes as fast as possible.That's why TrhoughSerial strategy is modified to check for new byte 10 times within required receive timeout. 
This single change reduces CPU load about 3 times (100%->30% on a 4-core i7 CPU with HT).
To lower CPU load even further the delayMicroseconds function is modified to work with minimum 50us sleeps. Hardware serial mitigates side effects of this change (reception is seamless) and in result CPU load goes down to 1 - 1.5%. 
@gioblu It's worth considering adding a pre-processor condition to lower …
> reduced CPU load for WINX86 interface utilizing TrhoughSerial strategy

- PJON.h
The response in receive function should be initialized otherwise PJON compiled on Windows may fail after couple hours of operation.
> FIX: uninitialized response causing run time check failure by VS

- examples/ARDUINO/Local/LoRa/BlinkTest/Receiver/Receiver.ino
- examples/ARDUINO/Local/LoRa/BlinkTest/Transmitter/Transmitter.ino
- examples/ARDUINO/Local/LoRa/HalfDuplex/Device1/Device1.ino
- examples/ARDUINO/Local/LoRa/HalfDuplex/Device2/Device2.ino
- examples/ARDUINO/Local/LoRa/HalfDuplexNoAcknowledge/Device1/Device1.ino
- examples/ARDUINO/Local/LoRa/HalfDuplexNoAcknowledge/Device2/Device2.ino
- examples/ARDUINO/Local/LoRa/JSON/Receiver/Receiver.ino
- examples/ARDUINO/Local/LoRa/JSON/Transmitter/Transmitter.ino
- examples/ARDUINO/Local/LoRa/NetworkAnalysis/Receiver/Receiver.ino
- examples/ARDUINO/Local/LoRa/NetworkAnalysis/Transmitter/Transmitter.ino
- examples/ARDUINO/Local/LoRa/Simplex/Receiver/Receiver.ino
- examples/ARDUINO/Local/LoRa/Simplex/Transmitter/Transmitter.ino
- strategies/LoRa/ThroughLora.h
- strategies/LoRa/Timing.h
- strategies/PJON_Strategies.h
To enable LoRa strategy "#define PJON_INCLUDE_TL" must be added in the
sketch.
About the frame separation. From what i understool, there's an internal frame buffer in lora hardware of 255 bytes, then the library polls this data from the fifo (or via interrupt) to arduino buffer. So the interface with PJON just polls data from the lora library buffer, so we have 2 buffers in total. One from PJON, and another from LoRa library. 
It would be more efficient maybe if it was possible to pass the LoRa buffer as PJON buffer, but it would imply changes to the lora library.
> Initial LoRa support

- examples/ARDUINO/Local/EthernetTCP/SoftwareBitBangSurrogate/Surrogate/Surrogate.ino
The surrogate can now support a RemoteWorker/master on for example a
Linux machine, using a higher level protocol with a dedicated port.
> Port support in Surrogate sketch

- src/strategies/LocalUDP/LocalUDP.h
We should change LUDP_RESPONSE_TIMEOUT to be overridable in the strategy. See also:
* https://github.com/gioblu/PJON/issues/222#issuecomment-410445654
* TS_RESPONSE_TIME_OUT
(we should also use a consistent naming; either TIMEOUT or TIME_OUT - not both)
> Make LUDP_RESPONSE_TIMEOUT overridable in strategy

- src/PJONDefines.h
Hi, I refresh MySensors transport based on PJON, address 0 is usually for gateway, and for broadcasting is 255, without this change I can't change that addresses.
> Allow change PJON_BROADCAST, PJON_MASTER_ID, PJON_NOT_ASSIGNED

- library.properties
When installing STM32duino using the instructions from http://wiki.stm32duino.com/index.php?title=Boards_Manager_package it installs the platform STM32F1 instead of stm32.
The one from github still used stm32 https://github.com/stm32duino/wiki/wiki/Getting-Started.
> Adds support for STM32-duino installed via the board.json

- src/strategies/PJON_Strategies.h
Excludes Ethernet from default strategies because of missing references (like ATtiny85).
Workaround so the examples compile at least until STM32 Ethernet gets fixed.
This only excludes STM32F1.
> STM32 Workarround for missing ethernet refernces

- src/PJONDefines.h
- src/interfaces/LINUX/PJON_LINUX_Interface.cpp
- src/interfaces/LINUX/PJON_LINUX_Interface.h
Pull request for issue #130.
When using PJON in a more complex linux project only this statement has to be added and the corresponding .cpp file needs to be linked:
```
#define PJON_LINUX_SEPARATE_DEFINITION
#include <PJON.h>
```
> split definition and declaration for linux interface

- src/strategies/SoftwareBitBang/Timing.h
Adding new timing constants for the ATMega328PB.
Please consider to remove mode 4 from the compatibility list, because this produces to much errors.
> #314: new timing constants for ATMega328PB

- src/interfaces/LINUX/PJON_LINUX_Interface.h
- src/interfaces/LINUX/PJON_LINUX_Interface.inl
with original implementation, convenient baud-rates of avr were not supported for linux serial interfaces. Therefore, I could not use PJON to communicate with my avr devices from my Linux PC.
The fix here allows to define a generic baud-rate for linux serial interfaces.
Tested with Linux ryzen5 5.5.13-arch1-1 on Arch Linux.
> use termios2 for generic baudrate support

- src/strategies/LocalFile/FileLockFunctions.h
Could casue conflicts in other headers included later
> Limited scope of some Windows-specific defines for LocalFile strategy

- src/strategies/SoftwareBitBang/README.md
point out PJDL is multi-controller bus (using oshwa terminology https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names/ )
> add column to PJDL vs 1-wire comparison

- src/interfaces/LINUX/PJON_LINUX_Interface.inl
This prevents linking errors if PJON is included in multiple compilation units.
Also using the static singleton pattern is safer than global vars, especially with multiple compilation units.
Currently projects cannot be linked if PJON.h is included in more than one cpp file, as global vars and function definitions will be there multiple times and cause conflicts.
One solution would be to separate function declarations and definitions into .h[pp] and .cpp files, however in your project you do not seem to use cpp files at all and also do not have a build system set up.
So to fix this I just used _inlining_ and the static singleton pattern (for global vars). This will effectively prevent linking errors (might cause some codesize increase).
> Prevent linking errors: Inline LINUX_Interface functions and remove global vars

- src/PJONDefines.h
fixes #406 
I tested this in my setup, using port 0,1 and 2. Now receiving works again :)
I also implemented it a little bit different that proposed in the issue.
I now use explicit re-initialization of the PacketInfo variable to avoid similar problems in other scenarios (packet-id, bus-id) which in my opinition might suffer from the same problem.
> Fix undefined behavior when using ports #406

- src/interfaces/ARDUINO/ESPNOWHelper.h
The ESPNow strategy uses old wifi_interface_t enums that have been removed/renamed in current version of ESP core, which causes compilation to fail  (believe these were first introduced in esp32 core v1.0.5)
Attached PR makes simple updates to address this, tested using the latest Arduino ESP32 v2.0.5 target board (based on ESP IDF Core v4.4.2), which makes the example compile and run (although some weirdness still remains, so it's possible that other changes are also required to update the strategy to current version)
> Fix ESPNow strategy to address breaking changes in ESP32 core
